import type { Metadata } from 'next';
import { Gelasio } from 'next/font/google';
import ConfigureAmplifyClientSide from './amplify-cognito-config';
import './globals.css';

export const gelasio = Gelasio({ subsets: ['latin'], weight: ['400', '500', '600', '700'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${gelasio.className} antialiased`}>
                <ConfigureAmplifyClientSide />
                {children}
            </body>
        </html>
    );
}
